
DROP SCHEMA `newdatabase`;
CREATE SCHEMA IF NOT EXISTS `newdatabase` DEFAULT CHARACTER SET utf8 ;
USE `newdatabase` ;

DROP TABLE IF EXISTS `newdatabase`.`ACL` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`ACL` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `model` varchar(512) DEFAULT NULL,
 `property` varchar(512) DEFAULT NULL,
 `accessType` varchar(512) DEFAULT NULL,
 `permission` varchar(512) DEFAULT NULL,
 `principalType` varchar(512) DEFAULT NULL,
 `principalId` varchar(512) DEFAULT NULL,
 PRIMARY KEY (`id`)
 ) ENGINE=InnoDB;



DROP TABLE IF EXISTS `newdatabase`.`AccessToken` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`AccessToken` (
   `id` varchar(255) NOT NULL,
   `ttl` int(11) DEFAULT NULL,
   `scopes` text,
   `created` datetime DEFAULT NULL,
   `userId` int(11) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB;


DROP TABLE IF EXISTS `newdatabase`.`User` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`User` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `realm` varchar(512) DEFAULT NULL,
   `username` varchar(512) DEFAULT NULL,
   `password` varchar(512) NOT NULL,
   `email` varchar(512) NOT NULL,
   `emailVerified` tinyint(1) DEFAULT NULL,
   `verificationToken` varchar(512) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB ;


DROP TABLE IF EXISTS `newdatabase`.`Role` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`Role` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `name` varchar(512) NOT NULL,
   `description` varchar(512) DEFAULT NULL,
   `created` datetime DEFAULT NULL,
   `modified` datetime DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB ;


DROP TABLE IF EXISTS `newdatabase`.`RoleMapping` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`RoleMapping` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `principalType` varchar(512) DEFAULT NULL,
   `principalId` varchar(255) DEFAULT NULL,
   `roleId` int(11) DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `principalId` (`principalId`)
 ) ENGINE=InnoDB;

-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 23:58:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



-- -----------------------------------------------------
-- Table `newdatabase`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`authority` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`authority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`crew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`crew` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`crew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`employee` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pin` INT NOT NULL,
  `is_employed` TINYINT NOT NULL DEFAULT 1,
  `is_working` TINYINT NOT NULL,
  `authority_id` INT NOT NULL,
  `crew_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pin_UNIQUE` (`pin` ASC),
  INDEX `fk_employee_authority1_idx` (`authority_id` ASC),
  INDEX `fk_employee_crew1_idx` (`crew_id` ASC),
  CONSTRAINT `fk_employee_authority1`
    FOREIGN KEY (`authority_id`)
    REFERENCES `newdatabase`.`authority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_crew1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `newdatabase`.`crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`shift` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clock_in_date` DATETIME NULL,
  `clock_out_date` DATETIME NULL,
  `length` INT NULL,
  `lunch` INT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shift_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_shift_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `newdatabase`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`category` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`dimension` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`dimension` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  `dimension_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC),
  INDEX `fk_subcategory_category1_idx` (`category_id` ASC),
  INDEX `fk_subcategory_dimension1_idx` (`dimension_id` ASC),
  CONSTRAINT `fk_subcategory_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `newdatabase`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcategory_dimension1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `newdatabase`.`dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`task` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `subcategory_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_subcategory1_idx` (`subcategory_id` ASC),
  CONSTRAINT `fk_task_subcategory1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `newdatabase`.`subcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`project` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`project_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`project_task` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`project_task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `quantity` INT NULL,
  `estimate_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_has_project_project1_idx` (`project_id` ASC),
  INDEX `fk_task_has_project_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_task_has_project_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `newdatabase`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `newdatabase`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newdatabase`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newdatabase`.`activity` ;

CREATE TABLE IF NOT EXISTS `newdatabase`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  `description` VARCHAR(180) NULL,
  `shift_id` INT NOT NULL,
  `project_task_id` INT NOT NULL,
  INDEX `fk_table1_shift1_idx` (`shift_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_activity_project_task1_idx` (`project_task_id` ASC),
  CONSTRAINT `fk_table1_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `newdatabase`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_project_task1`
    FOREIGN KEY (`project_task_id`)
    REFERENCES `newdatabase`.`project_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
