-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 17:15:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema timetrack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `timetrack` ;

-- -----------------------------------------------------
-- Schema timetrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timetrack` DEFAULT CHARACTER SET utf8 ;
USE `timetrack` ;

-- -----------------------------------------------------
-- Table `timetrack`.`crew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`crew` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`crew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `timetrack`.`crew` (`name` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`authority` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`authority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetrack`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`employee` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pin` INT NOT NULL,
  `is_employed` TINYINT NOT NULL,
  `is_working` TINYINT NOT NULL,
  `crew_id` INT NOT NULL,
  `authority_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_crew`
    FOREIGN KEY (`crew_id`)
    REFERENCES `timetrack`.`crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_authority1`
    FOREIGN KEY (`authority_id`)
    REFERENCES `timetrack`.`authority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `timetrack`.`employee` (`id` ASC);

CREATE UNIQUE INDEX `pin_UNIQUE` ON `timetrack`.`employee` (`pin` ASC);

CREATE INDEX `fk_employee_crew_idx` ON `timetrack`.`employee` (`crew_id` ASC);

CREATE INDEX `fk_employee_authority1_idx` ON `timetrack`.`employee` (`authority_id` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`shift` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clock_in_date` DATETIME NULL,
  `clock_out_date` DATETIME NULL,
  `length` INT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shift_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `timetrack`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_shift_employee1_idx` ON `timetrack`.`shift` (`employee_id` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`dimension` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`dimension` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetrack`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`category` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetrack`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `type_UNIQUE` ON `timetrack`.`subcategory` (`type` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`task` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NULL,
  `dimension_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_task_dimension1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `timetrack`.`dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `timetrack`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_subcategory1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `timetrack`.`subcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `timetrack`.`task` (`name` ASC);

CREATE INDEX `fk_task_dimension1_idx` ON `timetrack`.`task` (`dimension_id` ASC);

CREATE INDEX `fk_task_category1_idx` ON `timetrack`.`task` (`category_id` ASC);

CREATE INDEX `fk_task_subcategory1_idx` ON `timetrack`.`task` (`subcategory_id` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`project` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `is_active` TINYINT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetrack`.`shift_section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`shift_section` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`shift_section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `shift_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `timetrack`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shift_section_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `timetrack`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shift_section_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `timetrack`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_table1_shift1_idx` ON `timetrack`.`shift_section` (`shift_id` ASC);

CREATE INDEX `fk_shift_section_task1_idx` ON `timetrack`.`shift_section` (`task_id` ASC);

CREATE INDEX `fk_shift_section_project1_idx` ON `timetrack`.`shift_section` (`project_id` ASC);


-- -----------------------------------------------------
-- Table `timetrack`.`project_has_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetrack`.`project_has_task` ;

CREATE TABLE IF NOT EXISTS `timetrack`.`project_has_task` (
  `project_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `quantity` INT NULL,
  `estimate_time` INT NULL,
  PRIMARY KEY (`project_id`, `task_id`),
  CONSTRAINT `fk_project_has_task_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `timetrack`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_task_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `timetrack`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_project_has_task_task1_idx` ON `timetrack`.`project_has_task` (`task_id` ASC);

CREATE INDEX `fk_project_has_task_project1_idx` ON `timetrack`.`project_has_task` (`project_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
